name: poem
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20200225.2=hb1e8313_2
  - absl-py=0.11.0=py36h79c6626_0
  - altair=4.1.0=py_1
  - appnope=0.1.2=py36h79c6626_1
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=20.1.0=py36h6941dd6_2
  - arrow-cpp=2.0.0=py36hcd22ede_6_cpu
  - astor=0.8.1=pyh9f0ad1d_0
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - aws-c-common=0.4.59=hc929b4f_1
  - aws-c-event-stream=0.1.6=hc90cea0_6
  - aws-checksums=0.1.10=h38ed436_0
  - aws-sdk-cpp=1.8.70=h154b968_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - base58=2.1.0=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bleach=3.2.1=pyh9f0ad1d_0
  - blinker=1.4=py_1
  - boto3=1.16.51=pyhd8ed1ab_0
  - botocore=1.19.51=pyhd8ed1ab_0
  - brotli=1.0.9=h046ec9c_4
  - brotlipy=0.7.0=py36ha3de816_1001
  - bzip2=1.0.8=hc929b4f_4
  - c-ares=1.17.1=hc929b4f_0
  - ca-certificates=2020.12.8=hecd8cb5_0
  - cached-property=1.5.1=py_0
  - cachetools=4.1.1=py_0
  - certifi=2020.12.5=py36hecd8cb5_0
  - cffi=1.14.4=py36hfe0777f_1
  - chardet=4.0.0=py36h79c6626_1
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.3.1=py36hd858a44_1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=h3f75d11_0
  - gast=0.2.2=py36_0
  - gflags=2.2.2=hb1e8313_1004
  - gitdb=4.0.5=py_0
  - gitpython=3.1.12=pyhd8ed1ab_0
  - glog=0.4.0=hb7f4fc5_3
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpc-cpp=1.33.2=h0202f98_1
  - grpcio=1.31.0=py36h7580e61_0
  - h5py=2.10.0=py36h0601b69_1
  - hdf5=1.10.6=nompi_h3e39495_100
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.4.0=py36h79c6626_0
  - importlib_metadata=3.4.0=hd8ed1ab_0
  - ipykernel=5.4.2=py36h9cf137f_0
  - ipython=7.12.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jedi=0.18.0=py36h79c6626_2
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=hbcb3906_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.0=py36h79c6626_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_1
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.1.0=py_0
  - krb5=1.17.2=h60d9502_0
  - lcms2=2.11=h11f7e16_1
  - libblas=3.9.0=7_openblas
  - libcblas=3.9.0=7_openblas
  - libcurl=7.71.1=h9bf37e3_8
  - libcxx=11.0.0=h4c3b8ed_1
  - libedit=3.1.20191231=h1de35cc_1
  - libev=4.33=haf1e3a3_1
  - libevent=2.1.10=hddc9c9b_3
  - libffi=3.3=hb1e8313_2
  - libgfortran=4.0.0=h1a10cd1_15
  - libgfortran4=7.5.0=h1a10cd1_15
  - liblapack=3.9.0=7_openblas
  - libnghttp2=1.41.0=h7580e61_2
  - libopenblas=0.3.12=openmp_h63d9170_1
  - libpng=1.6.37=h7cec526_2
  - libprotobuf=3.13.0.1=hab81aa3_0
  - libsodium=1.0.18=hbcb3906_1
  - libssh2=1.9.0=h8a08a2b_5
  - libthrift=0.13.0=h990abc0_6
  - libtiff=4.2.0=h355d032_0
  - libutf8proc=2.6.1=h35c211d_0
  - libwebp-base=1.1.0=hbcb3906_3
  - llvm-openmp=11.0.0=h73239a0_1
  - lz4-c=1.9.2=hb1e8313_3
  - markdown=3.3.3=pyh9f0ad1d_0
  - markupsafe=1.1.1=py36h20b66c6_3
  - mistune=0.8.4=py36h20b66c6_1003
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py36h79c6626_3
  - nbformat=5.0.8=py_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - nomkl=3.0=0
  - notebook=6.1.6=py36h79c6626_0
  - numpy=1.19.5=py36h08dc641_1
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1i=h9ed2024_0
  - opt_einsum=3.1.0=py_0
  - orc=1.6.5=h4465734_0
  - packaging=20.8=pyhd3deb0d_0
  - pandas=1.1.5=py36h2be6da3_0
  - pandoc=2.11.3.2=h35c211d_0
  - pandocfilters=1.4.2=py_1
  - parquet-cpp=1.5.1=2
  - parso=0.8.1=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=7.0.0=py36h4655f20_0
  - pip=20.3.3=py36hecd8cb5_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.10=pyha770c72_0
  - prompt_toolkit=3.0.10=hd8ed1ab_0
  - protobuf=3.13.0.1=py36hb1e8313_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyarrow=2.0.0=py36h10944bd_6_cpu
  - pycparser=2.20=pyh9f0ad1d_2
  - pydeck=0.5.0=pyh9f0ad1d_0
  - pygments=2.7.3=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py36h20b66c6_2
  - pysocks=1.7.1=py36h79c6626_3
  - python=3.6.12=h26836e1_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.5=pyhd8ed1ab_0
  - pyyaml=5.3.1=py36h20b66c6_2
  - pyzmq=20.0.0=py36h6ad5393_1
  - re2=2020.11.01=h2e338ed_0
  - readline=8.0=h1de35cc_0
  - requests=2.25.1=pyhd3deb0d_0
  - s3transfer=0.3.3=pyhd8ed1ab_5
  - scipy=1.4.1=py36h1dac7e4_3
  - send2trash=1.5.0=py_0
  - setuptools=51.1.2=py36hecd8cb5_3
  - six=1.15.0=pyh9f0ad1d_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - snappy=1.1.8=hb1e8313_3
  - sqlite=3.33.0=hffcf06c_0
  - streamlit=0.74.1=pyhd8ed1ab_0
  - tensorboard=1.15.0=pyhb230dea_0
  - tensorflow=1.15.0=mkl_py36h975b573_0
  - tensorflow-base=1.15.0=mkl_py36h032239d_0
  - tensorflow-estimator=1.15.1=pyh2649769_0
  - termcolor=1.1.0=py_2
  - terminado=0.9.2=py36h79c6626_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hb0a8c7a_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py36h20b66c6_1
  - traitlets=4.3.3=py36h9f0ad1d_1
  - typing_extensions=3.7.4.3=py_0
  - tzlocal=2.1=pyh9f0ad1d_0
  - urllib3=1.26.2=pyhd8ed1ab_0
  - validators=0.18.2=pyhd3deb0d_0
  - watchdog=1.0.2=py36h20b66c6_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=0.16.1=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py36h79c6626_4
  - wrapt=1.12.1=py36h20b66c6_3
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.3=h74dc148_3
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.8=h62961b2_0
prefix: /Users/sauravmaheshkar/opt/anaconda3/envs/poem
